# Generated by Django 3.1.1 on 2021-03-19 07:28

import culinary_post.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulinaryPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Заголовок должен быть минимуи 10 символов', max_length=1000, validators=[culinary_post.models.validate_max_len], verbose_name='Загаловок')),
                ('content', models.TextField(verbose_name='Описания')),
                ('image', models.ImageField(blank=True, upload_to='posts', verbose_name='Фотография')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culinary_post', to='contact.userprofile')),
                ('liked', models.ManyToManyField(blank=True, related_name='post_likes', to='contact.UserProfile')),
            ],
            options={
                'verbose_name': 'Кулинарный пост',
                'verbose_name_plural': 'Кулинарные посты',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culinary_post.culinarypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.userprofile')),
            ],
            options={
                'verbose_name': ' Лайки к посте',
                'verbose_name_plural': 'Лайки к постам',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culinary_post.culinarypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culinary_comment', to='contact.userprofile')),
            ],
            options={
                'verbose_name': 'Коментария к посту',
                'verbose_name_plural': 'Коментарии к постам',
            },
        ),
    ]
