# Generated by Django 3.1.1 on 2021-03-28 16:34

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('culinary_post', '0003_postcomment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulinaryPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Написать комментарии')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.userprofile', verbose_name='Автор')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='culinary_post.culinarypost', verbose_name='Пост')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='culinary_post.culinarypostcomment', verbose_name='Родитель')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
