# Generated by Django 3.1.1 on 2021-03-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_post', '0004_auto_20210328_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culinarypostcomment',
            old_name='meal',
            new_name='post',
        ),
    ]
