# Generated by Django 3.1.1 on 2021-04-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_post', '0005_auto_20210328_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culinarypostcomment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
