# Generated by Django 3.1.1 on 2021-03-13 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_recipe', '0004_auto_20210313_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='culinary_recipe.subcategory', verbose_name='Подкатегория'),
        ),
    ]
