# Generated by Django 3.1.1 on 2021-03-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_recipe', '0007_auto_20210313_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, verbose_name='Количество'),
        ),
    ]
