# Generated by Django 3.1.1 on 2021-04-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_recipe', '0008_auto_20210314_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='Occasion',
            field=models.ManyToManyField(blank=True, to='culinary_recipe.Occasion', verbose_name='Повод'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='servings',
            field=models.SmallIntegerField(verbose_name='Количество порций'),
        ),
    ]
