# Generated by Django 3.1.1 on 2021-04-14 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_recipe', '0010_auto_20210413_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['id'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['id'], 'verbose_name': 'Пошаговый рецепт', 'verbose_name_plural': 'Пошаговый рецепты'},
        ),
    ]
