# Generated by Django 3.1.1 on 2021-03-15 06:47

import contact.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('culinary_recipe', '0008_auto_20210314_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Имя для урл')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=250, verbose_name='Маил')),
                ('country_of_birth', models.CharField(blank=True, max_length=150, null=True, verbose_name='Страна проживания')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('avatar', models.ImageField(blank=True, default='avatar_man.png', upload_to=contact.models.get_profile_image_filepath, verbose_name='Аватар профиль')),
                ('gender', models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=1, verbose_name='Пол')),
                ('profession', models.TextField(blank=True, help_text='Это поле необезательное', max_length='1000', verbose_name='Профессия')),
                ('interest', models.TextField(blank=True, help_text='Это поле необезательное', max_length='1000', verbose_name='Интересы')),
                ('about', models.TextField(blank=True, help_text='Это поле необезательное', max_length='1000', verbose_name='О себе')),
                ('get_news_from', models.BooleanField(default=False, verbose_name='Получать уведомления')),
                ('get_notification_about_comments', models.BooleanField(default=False, verbose_name='Получать уведомления о комментах')),
                ('get_notification_friend_request', models.BooleanField(default=False, verbose_name='Получать уведомления на добавление в дружбу')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('dishes', models.ManyToManyField(blank=True, to='culinary_recipe.Dish')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='Друзья')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Профиль пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], max_length=9, verbose_name='Статус')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='contact.userprofile', verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='contact.userprofile', verbose_name='Отправитель')),
            ],
        ),
    ]
