# Generated by Django 3.1.1 on 2021-03-05 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('poster', models.ImageField(upload_to='category/', verbose_name='Постер для категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Страна')),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Названия устройтсва')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Поле для урл')),
            ],
            options={
                'verbose_name': 'Устройство',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Поле для урл')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='meal/', verbose_name='Постер')),
                ('preparation_time_hour', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Время подготовки')),
                ('preparation_time_minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cooking_time_hour', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Время готовки')),
                ('cooking_time_minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('servings', models.SmallIntegerField(default='5', verbose_name='Количество порций')),
                ('complexity', models.CharField(blank=True, choices=[('легко', 'легко'), ('средне', 'средне'), ('сложно', 'сложно')], max_length=7, verbose_name='Сложность приготовления')),
                ('vegetarian', models.CharField(blank=True, choices=[('нет', 'нет'), ('лакто', 'лакто'), ('ово', 'ово'), ('ово-лакто', 'ово-лакто'), ('пескетарианство', 'пескетарианство'), ('(допускается рыба)', '(допускается рыба)'), ('строго', 'строго')], max_length=20, verbose_name='Вегетарианство')),
                ('calorie', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Калория')),
                ('protein', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Протеин')),
                ('fat', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Жиры')),
                ('carbohydrate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Углеводы')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('moderator', models.BooleanField(default=False, verbose_name='Модератор')),
                ('advice', models.TextField(blank=True, verbose_name='Полезные советы')),
                ('is_liked', models.BooleanField(default=False)),
                ('dish_added', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='culinary_recipe.category', verbose_name='Категория')),
                ('country', models.ForeignKey(help_text='(необязательное поле)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='culinary_recipe.country', verbose_name='Страна')),
                ('device', models.ManyToManyField(blank=True, to='culinary_recipe.Device', verbose_name='Устройтво')),
                ('likes', models.ManyToManyField(related_name='meal_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайк')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюды',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Мера веса/объема')),
            ],
            options={
                'verbose_name': 'Мера веса/объема',
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Повод')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Поле для урл')),
            ],
            options={
                'verbose_name': 'Повод',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Названия технологии')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Поле для урл')),
            ],
            options={
                'verbose_name': 'Технология',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Поле для урл')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='culinary_recipe.category', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='steps/', verbose_name='Фото')),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='culinary_recipe.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Пошаговый рецепт',
                'verbose_name_plural': 'Пошаговый рецепты',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Название')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, verbose_name='Количество')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='culinary_recipe.dish', verbose_name='Блюдо')),
                ('measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='culinary_recipe.measure', verbose_name='Мера веса/объема')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='DishLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culinary_recipe.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' Лайки к рецепту',
                'verbose_name_plural': 'Лайки к рецептам',
            },
        ),
        migrations.CreateModel(
            name='DishComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Написать комментарии')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='culinary_recipe.dish', verbose_name='Блюдо')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='culinary_recipe.dishcomment', verbose_name='Родитель')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='culinary_recipe.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='dish',
            name='technology',
            field=models.ManyToManyField(blank=True, to='culinary_recipe.Technology', verbose_name='Технология'),
        ),
    ]
