# Generated by Django 3.1.1 on 2021-03-06 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Сложность приготовления')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Поле для урл')),
            ],
            options={
                'verbose_name': 'Сложность приготовления',
                'verbose_name_plural': 'Сложность приготовления',
            },
        ),
        migrations.CreateModel(
            name='Vegeterian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Вегетарианство')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Поле для урл')),
            ],
            options={
                'verbose_name': 'Вегетарианство',
                'verbose_name_plural': 'Вегетарианство',
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterModelOptions(
            name='occasion',
            options={'verbose_name': 'Повод', 'verbose_name_plural': 'Повод'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Технология', 'verbose_name_plural': 'Технологии'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='complexity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='culinary_recipe.complexity', verbose_name='Сложность приготовления'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='vegetarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='culinary_recipe.vegeterian', verbose_name='Вегетарианство'),
        ),
    ]
