# Generated by Django 3.1.1 on 2021-03-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_recipe', '0005_auto_20210313_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages={'required': 'это поле только числовое значение'}, max_digits=1000, verbose_name='Количество'),
        ),
    ]
